### ISSUE TITLE
Sign not allowed in string format specifier

### ISSUE THREAD

**Issue by crowell** [zachriggle/pwndbg#9]
debugging radare2

```
pwn> p img_dbg_dir_entry 
$2 = (Pe32_image_debug_directory_entry *) 0x6e8ca0
Python Exception <class 'ValueError'> Sign not allowed in string format specifier:
```
on file #2  0x00007ffff70077c5 in Pe32_r_bin_pe_get_debug_data (bin=0x6e8ab0, res=0x7fffffffd280) at /home/jeff/ctf/tools/radare2/libr/..//libr/bin/p/../format/pe/pe.c:1911

ping me for more details for this.

**Comment by crowell** [comment]
this actually looks like it may be due to integration with `cgdb`

**Comment by zachriggle** [comment]
Could you clarify?

**Comment by crowell** [comment]
sorry, was pretty dead when I reported that :]
this is certainly due to cgdb, so you can probably just close this.
easy reproducible steps:

```sh
cgdb /bin/ls
source ~/path/to/pwndbg/gdbinit.py
start
```

```
(gdb) source ~/tools/pwndbg/gdbinit.py 
[31mLoaded 39 commands.  Type pwndbg for a list.[0m
pwn> start
Temporary breakpoint 1 at 0x402168
Python Exception <type 'exceptions.ValueError'> Sign not allowed in string format specifier:
```

cgdb also doesn't support colors, so using pwndbg with it is kind of silly.

**Comment by zachriggle** [comment]
Closing this as wontfix, as it doesn't affect `gdb`.
